### ISSUE TITLE
Remove metrics?

### ISSUE THREAD

**Issue by abhishekchak52** [compsoc-ssc/compsocssc#11]
Should we remove metrics? Does it serve a purpose? @theSage21 @libhide

**Comment by libhide** [comment]
It can be (and should be) removed.

**Comment by theSage21** [comment]
Yep. Something more elegant should be used.

**Comment by libhide** [comment]
Knock knock @deadbeatfour - please remove metrics and close this issue.

**Comment by ghost** [comment]
Isn't metrics already commented out?

**Comment by libhide** [comment]
Yeah, but its a useless app now so we can get rid of it. 
I feel like, let's do a major cleanup feature branch and get rid of unwanted things. Thoughts?

**Comment by libhide** [comment]
Just saw you deleted it in #16 so that's cool. Yeah, we needed to delete it.
