### ISSUE TITLE
(master) requirements.txt requires matplotlib?

### ISSUE THREAD

**Issue by ghost** [compsoc-ssc/compsocssc#12]
In `compsocssc/events/orfik/utils.py` `matplotlib` is imported, which was not installed by `requirements.txt.`
This is the traceback I get when trying to access root for the first time:

> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
>   119.                 resolver_match = resolver.resolve(request.path_info)
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/site-packages/django/core/urlresolvers.py" in resolve
>   366.             for pattern in self.url_patterns:
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/site-packages/django/core/urlresolvers.py" in url_patterns
>   402.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/site-packages/django/core/urlresolvers.py" in urlconf_module
>   396.             self._urlconf_module = import_module(self.urlconf_name)
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/importlib/__init__.py" in import_module
>   126.     return _bootstrap._gcd_import(name[level:], package, level)
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/website/urls.py" in <module>
>   14.     url(r'^events/', include('events.urls', namespace='events')),
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/site-packages/django/conf/urls/__init__.py" in include
>   33.         urlconf_module = import_module(urlconf_module)
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/importlib/__init__.py" in import_module
>   126.     return _bootstrap._gcd_import(name[level:], package, level)
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/events/urls.py" in <module>
>   9.     url(r'^orfik/', include('events.orfik.urls', namespace='orfik')),
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/site-packages/django/conf/urls/__init__.py" in include
>   33.         urlconf_module = import_module(urlconf_module)
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/django/lib/python3.5/importlib/__init__.py" in import_module
>   126.     return _bootstrap._gcd_import(name[level:], package, level)
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/events/orfik/urls.py" in <module>
>   2. from events.orfik import views
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/events/orfik/views.py" in <module>
>   10. from events.orfik import models, utils
> File "/mnt/c/Users/Utkarsh/Documents/venv/comps/compsocssc/events/orfik/utils.py" in <module>
>   4. import matplotlib.pyplot as plt
> 
> Exception Type: ImportError at /
> Exception Value: No module named 'matplotlib'

**Comment by theSage21** [comment]
Add it to the req? PR welcome.

**Comment by ghost** [comment]
`pandas` module also requires to be added to requirements.txt

**Comment by theSage21** [comment]
Yep yep. These were added to include nice leaderboard graphs for orfik.
