### ISSUE TITLE
bash script appending '\r' at every line

### ISSUE THREAD

**Issue by ghost** [compsoc-ssc/compsocssc#15]
The code is unable to compile due to this problem.
![bug1](https://user-images.githubusercontent.com/25015384/34431369-9fe4cf96-ec94-11e7-9d40-c788ee2616f8.GIF)

**Comment by abhishekchak52** [comment]
I think this is specific to the text editor you're using. Save files with *nix line endings instead of windows, then check

**Comment by ghost** [comment]
I didn't edit the setup.sh file.

**Comment by ghost** [comment]
Apparently someone edited setup.sh in an editor which considers dos's ```\n\r``` as newline and not unix's ```\n```.
I rewrote the file in ```nano``` editor and now hopefully it works.

**Comment by ghost** [comment]
Need to do a PR on ```level_up``` ?
